### ISSUE TITLE
Ansible Network Connection Plugin need to be refined handling status logic. (#82391)

### ISSUE THREAD

**Issue by vikramsubramanian** [Mayil-AI-Sandbox/ansible-demo#22]
### Summary

- Ansible connection helper regards the task status as "failed" when network appliances output includes specific keywords like “error”.  However, even if those outputs include "error" words, some commands succeed in running actually. 

### Issue Type

Feature Idea

### Component Name

ansible.module_utils.connection

### Additional Information

In this case, the below playbook will be regarded as `failed` because `request support information` command will include `error` words. However, `request support information` command itself actually succeeds.

```yaml 
- name: Capture support information
  junipernetworks.junos.junos_command:
    commands: "request support information"
```

Looking at the source code, I see this comes from the below logic. Are there any other ideas to handle tasks to avoid `failed` for the above case?
https://github.com/ansible/ansible/blob/v2.16.1/lib/ansible/module_utils/connection.py#L196

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
)
