### ISSUE TITLE
error not returned if jinja default used (#82389)

### ISSUE THREAD

**Issue by vikramsubramanian** [Mayil-AI-Sandbox/ansible-demo#24]
### Summary

When using jinja variable with default i.e. `{{ non_existing_var_random_name | default('any type or value') }}` and the variable would have created an error if default was not specified. No error is returned and the default value as specified is returned.

using `ignore_errors=false` has no effect.

### Issue Type

Bug Report

### Component Name

ansible-core

### Ansible Version

```console
$ (python_venv) sysadmin@laptop2:~/git/project-production$ ansible --version
ansible [core 2.16.1]
  config file = /home/sysadmin/git/project-production/ansible.cfg
  configured module search path = ['/home/sysadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sysadmin/git/python_venv/lib/python3.11/site-packages/ansible
  ansible collection location = /etc/ansible/collections:/runner/collections:/home/sysadmin/.ansible/collections/ansible_collections
  executable location = /home/sysadmin/git/python_venv/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/sysadmin/git/python_venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
(python_venv) sysadmin@laptop2:~/git/project-production$
```

### Configuration

```console
(python_venv) sysadmin@laptop2:~/git/project-production$ ansible-config dump --only-changed -t all
COLLECTIONS_PATHS(/home/sysadmin/git/project-production/ansible.cfg) = ['/etc/ansible/collections', '/runner/collections', '/home/sysadmin/.ansible/collections/ansible_collections']
CONFIG_FILE() = /home/sysadmin/git/project-production/ansible.cfg
DEFAULT_LOG_PATH(/home/sysadmin/git/project-production/ansible.cfg) = /home/sysadmin/ansible.log
DEFAULT_ROLES_PATH(/home/sysadmin/git/project-production/ansible.cfg) = ['/etc/ansible/roles', '/runner/roles', '/workdir/roles', '/home/sysadmin/aa-shits-and-gigs/ansible-roles-repo']
HOST_KEY_CHECKING(/home/sysadmin/git/project-production/ansible.cfg) = False
INVENTORY_ENABLED(/home/sysadmin/git/project-production/ansible.cfg) = ['yaml', 'script']
INVENTORY_IGNORE_PATTERNS(/home/sysadmin/git/project-production/ansible.cfg) = ['gitlab-ci/*']
SHOW_CUSTOM_STATS(/home/sysadmin/git/project-production/ansible.cfg) = True

CALLBACK:
========

default:
_______
show_custom_stats(/home/sysadmin/git/project-production/ansible.cfg) = True

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/sysadmin/git/project-production/ansible.cfg) = False

ssh:
___
host_key_checking(/home/sysadmin/git/project-production/ansible.cfg) = False
```

### OS / Environment

debian 12 Bash and AWX 23.5.1

### Steps to Reproduce

```yaml (paste below)
---
- name: Test hiding error with default
  hosts: localhost
  gather_facts: true
  vars:
    ansible_connection: local
    existing_var_random_name: 
      - 'a value here'
      - 'b value here'
      - "{{ this_var_doesnt_exist }}"


  tasks:


    - name: debug existing var with undefined var that should error
      ansible.builtin.debug:
        msg: 
        - "{{ existing_var_random_name | default([]) }}" 
        - "{{ existing_var_random_name | default([]) | length }}" 
        - "{{ existing_var_random_name | default([]) | length | int }}" 
        - "{{ existing_var_random_name | default([]) | length | int > 0 }}" 


    - name: debug existing var with undefined var that should error (ignore_error=false)
      ansible.builtin.debug:
        msg: 
        - "{{ existing_var_random_name | default([]) }}" 
        - "{{ existing_var_random_name | default([]) | length }}" 
        - "{{ existing_var_random_name | default([]) | length | int }}" 
        - "{{ existing_var_random_name | default([]) | length | int > 0 }}"
      ignore_errors: false


    - name: debug should error but doesn't string
      ansible.builtin.debug:
        msg: 
        - "{{ existing_var_random_name| default('string') }}" 


    - name: debug now shows error as default not hiding
      ansible.builtin.debug:
        msg: 
        - "{{ existing_var_random_name }}" 
        - "{{ existing_var_random_name | default([]) }}" 
        - "{{ existing_var_random_name | default([]) | length }}" 
        - "{{ existing_var_random_name | default([]) | length | int }}" 
        - "{{ existing_var_random_name | default([]) | length | int > 0 }}" 

```

`ansible-playbook test.yaml -vvv`

### Expected Results

that if an error would have been presented if `default()` was not used, that the error still be presented if `default()` is used

### Actual Results

```console
ansible-playbook [core 2.16.1]
  config file = /home/sysadmin/git/project-production/ansible.cfg
  configured module search path = ['/home/sysadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sysadmin/git/python_venv/lib/python3.11/site-packages/ansible
  ansible collection location = /etc/ansible/collections:/runner/collections:/home/sysadmin/.ansible/collections/ansible_collections
  executable location = /home/sysadmin/git/python_venv/bin/ansible-playbook
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/sysadmin/git/python_venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /home/sysadmin/git/project-production/ansible.cfg as config file
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: backup-test.yaml ****************************************************************************************************************************************************************************************
1 plays in /home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml

PLAY [Test hiding error with default] *****************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
task path: /home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: sysadmin
<127.0.0.1> EXEC /bin/sh -c 'echo ~sysadmin && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/sysadmin/.ansible/tmp `"&& mkdir "` echo /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921 `" && echo ansible-tmp-1702141519.557717-224195-172826351344921="` echo /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921 `" ) && sleep 0'
Using module file /home/sysadmin/git/python_venv/lib/python3.11/site-packages/ansible/modules/setup.py
<127.0.0.1> PUT /home/sysadmin/.ansible/tmp/ansible-local-224192wmwwgrik/tmpb7pwpm6k TO /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921/ /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/sysadmin/git/python_venv/bin/python3 /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/sysadmin/.ansible/tmp/ansible-tmp-1702141519.557717-224195-172826351344921/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [debug existing var with undefined var that should error] ****************************************************************************************************************************************************
task path: /home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml:16
ok: [localhost] => {
    "msg": [
        [],
        "0",
        "0",
        false
    ]
}

TASK [debug existing var with undefined var that should error (ignore_error=false)] *******************************************************************************************************************************
task path: /home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml:25
ok: [localhost] => {
    "msg": [
        [],
        "0",
        "0",
        false
    ]
}

TASK [debug should error but doesn't string] **********************************************************************************************************************************************************************
task path: /home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml:35
ok: [localhost] => {
    "msg": [
        "string"
    ]
}

TASK [debug now shows error as default not hiding] ****************************************************************************************************************************************************************
task path: /home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml:41
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: ['a value here', 'b value here', '{{ this_var_doesnt_exist }}']: 'this_var_doesnt_exist' is undefined. 'this_var_doesnt_exist' is undefined. ['a value here', 'b value here', '{{ this_var_doesnt_exist }}']: 'this_var_doesnt_exist' is undefined. 'this_var_doesnt_exist' is undefined\n\nThe error appears to be in '/home/sysadmin/aa-shits-and-gigs/repo.ansible_playbooks/backup-test.yaml': line 41, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: debug now shows error as default not hiding\n      ^ here\n"
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

edit: 
1. added awx environment
2. Added the correct playbook (and play output) as its the nested var that creates the error that should not be hidden.
)
