### ISSUE TITLE
Getting DiskUseage of Alpine Linux LXC containers fails: 'dict object' has no attribute 'stdout'  (#82457)

### ISSUE THREAD

**Issue by vikramsubramanian** [Mayil-AI-Sandbox/ansible-demo#4]
### Summary

The issue seems to be realy often happen here but I can't find someone that got it on a diskuseage report.

### Issue Type

Bug Report

### Component Name

df

### Ansible Version

```console
$ ansible --version

ansible [core 2.14.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.9.18 (main, Sep  7 2023, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3

CALLBACK:
========

default:
_______
display_skipped_hosts(/etc/ansible/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/etc/ansible/ansible.cfg) = False

ssh:
___
host_key_checking(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

Ansible is running on AlmaLinux 9.3

### Steps to Reproduce

```yaml
---
- name: Check Disk Space
  hosts: Jake
  gather_facts: true

  tasks:
    - name: Get Disk Usage
      command: df -h
      register: disk_usage
    - name: Check Disk Space available
      shell: df -h / | awk 'NR==3 {print $4}'
      register: disk_usage
      when: ansible_os_family == 'Alpine'
    - name: Check Disk Space available
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage
      when: ansible_os_family != 'Alpine'
    - debug:
        msg: "Disk space on {{ inventory_hostname }} is above 80%!"
      when: disk_usage.stdout[:-1]|int > 80
```

### Expected Results

It should tell me when the diskuseage on / is higher than 80%

### Actual Results

```console
FAILED! => {"msg": "The conditional check 'disk_usage.stdout[:-1]|int > 80' failed. The error was: error while evaluating conditional (disk_usage.stdout[:-1]|int > 80): 'dict object' has no attribute 'stdout'. 'dict object' has no attribute 'stdout'\n\nThe error appears to be in '/opt/semaphore/repository_34_70/playbooks/checkdiskspace.yaml': line 18, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n when: ansible_os_family != 'Alpine'\n - debug:\n ^ here\n"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
)
